Update Docker instructions to checkout 5.4 (#515)
In 5.4 the `switch_blog` action received a third argument. Running this environment with anything prior causes `wcorg_switch_to_blog_locale()` to cause a fatal error, which breaks WP-CLI/setup flow.

```bash
docker-compose exec wordcamp.test wp site list --field=url --allow-root

Fatal error: Uncaught ArgumentCountError: Too few arguments to function wcorg_switch_to_blog_locale(), 2 passed in /usr/src/public_html/mu/wp-includes/class-wp-hook.php on line 286 and exactly 3 expected in /usr/src/public_html/wp-content/mu-plugins/wcorg-misc.php:318
```